### ISSUE TITLE
drawRect Memory Leak

### ISSUE THREAD

**Issue by crossdeveloper** [prscX/PXSiriWave9#1]
on drawRect function, occurs memory leak
please add release functions. 

CGPathRelease(path);
... ...
CGColorSpaceRelease(colorSpaceRef);
CGGradientRelease(gradient);

**Comment by alexwasner** [comment]
Wondering where this leak came from. Thanks @crossdeveloper

**Comment by crossdeveloper** [comment]
I attached above. on DrawRect function. the above code should be added.

**Comment by crossdeveloper** [comment]
Garbage paths, colorSpaceRef and gradient objects should be released. Thanks.

**Comment by prscX** [comment]
Thanks @crossdeveloper for raising issue and providing the solution.

I have pushed a release with provided solution. Now you can install latest version `0.0.2` and verify the same.

[0.0.2](https://github.com/prscX/PXSiriWave9/releases/tag/v0.0.2)

Thanks
</ Pranav >
